# Generated by Django 5.0.13 on 2025-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(blank=True, max_length=150)),
                ('broj_mobitela', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Korisnici',
            },
        ),
    ]
