# Generated by Django 5.0.13 on 2025-06-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='album'),
        ),
    ]
